### ISSUE TITLE
Rework map generation

### ISSUE THREAD

**Issue by TheImmortalKing** [GDcheeriosYT/The-Backrooms#21]
With normal lighting and texture

**Comment by GDcheerios** [comment]
- [x] add dark spaces and lit spaces
- [x] add doorway prefab
- [x] make chunk walls
- [x] fix lighting
- [x] prevent walls spawning inside each other

New idea:

Chunks randomize like this
There can be up to 4 sides of a chunk if there is 4 there must be a door. Must be at least 1 wall in a chunk

Drawing example ![Screenshot_20220220-173343_Samsung Notes.jpg](https://user-images.githubusercontent.com/54640414/154869338-5bfd5c12-190d-44f0-8bfa-216da4763bf7.jpg)

**Comment by GDcheerios** [comment]
To fix walls spawning inside each other I will probably just from the top left to bottom right spawn walls in a |^- form
